version: '3.5'
services:
  app:
    build: .
  sut:
    image: alpine:3.19
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - type: bind
        source: ../.
        target: /srv/app
