version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: ${PROJECT}
    ports:
      - "${PROJECT_PORT}:3306"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql
      - ~/mysql-data:/docker-entrypoint-initdb.d

volumes:
    data: