version: "3.8"

services:
  node:
    image: ${PROJECT}
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${PROJECT}
    ports:
      - ${PROJECT_PORT}:80
    volumes:
      - type: bind
        source: ../
        target: /var/www/html
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:${PROJECT_PORT}/fpm-ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    tty: true
