version: '3.8'

services:
  cache:
    image: redis:${PROJECT}
    container_name: ${PROJECT}
    restart: always
    ports:
      - ${PROJECT_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DB_PASSWORD}
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
