version: "3.8"

services:
    nginx:
      image: nginx-1.24:alpine-3.19
      build:
        context: ./docker/nginx
        dockerfile: Dockerfile
      container_name: ${PROJECT}
      depends_on:
        - php
      volumes:
        - .:/var/www:cached
      ports:
        - ${PROJECT_PORT}:80

    php:
      image: php-8.2:alpine-3.19
      build:
        context: ./docker/php
        args:
          USER_ID: ${USER_ID:-1000}
          GROUP_ID: ${GROUP_ID:-1000}
      container_name: ${PROJECT}-php
      volumes:
        - .:/var/www:cached
